version: 0.2
os: linux
files:
  - source: /Templates/en/
    destination: /var/www/aws-test.com/html/ 
    overwrite: true  
permissions:
   - object: /var/www/aws-test.com/html/
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root
