version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python setup.py build
  post_build:
    commands:
      - python setup.py install
