version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
      - pip install pylint
      - pip install html5validator
  build:
    commands:
      - pylint --disable=all --enable=F,E,W,R,C app.py 
      - html5validator --show-warnings Templates/en/index.html
