version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - pylint app.py  # Ejecutar el análisis estático del código con Pylint
      - python -m pytest
